# Build from official WordPress image
FROM wordpress:latest
MAINTAINER MAPC Digital Services Team

# Download PHP LDAP extension
RUN apt-get update;
RUN apt-get install -y libldap2-dev;
RUN rm -rf /var/lib/apt/lists/*;
# Configure and install PHP LDAP extension
RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/;
RUN docker-php-ext-install ldap;
